use crate::ai::BossAi;
use crate::board::UpdateCommand;
use crate::sprite::Cell;
use crate::sprite::Sprite;
use crate::sprite::SpriteState;
use crate::util::{Direction, Point};
use tui::style::Color;

pub struct Boss {
    pub state: SpriteState,
    pub ai: BossAi,
}

impl Boss {
    pub fn new_boss(x: i16, y: i16, x_range: &(i16, i16), y_range: &(i16, i16)) -> Self {
        Boss {
            state: SpriteState {
                id: 0,
                hp: 20,
                pos: Point::new(x, y),
                direction: Direction::Down,
                cells: vec![
                    vec![
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("+", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("+", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                    ],
                    vec![
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("/", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("\\", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                    ],
                    vec![
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("/", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("/", Color::Yellow),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("\\", Color::Yellow),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("\\", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                    ],
                    vec![
                        Cell::new("+", Color::LightCyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("+", Color::LightGreen),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(":", Color::White),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("+", Color::LightGreen),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("=", Color::Cyan),
                        Cell::new("+", Color::LightCyan),
                    ],
                    vec![
                        Cell::new("V", Color::Red),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("", Color::Green),
                        Cell::new("\\", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("\\", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("_", Color::Yellow),
                        Cell::new("/", Color::Yellow),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("/", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("V", Color::Red),
                    ],
                    vec![
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("\\", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("/", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                    ],
                    vec![
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new("+", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("~", Color::Green),
                        Cell::new("+", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                        Cell::new(" ", Color::Green),
                    ],
                ],
            },
            ai: BossAi::new(x_range, y_range, 2, 1.0),
        }
    }
}

impl<'a> Sprite<'a> for Boss {
    fn set_id(&mut self, id: u32) {
        self.state.id = id;
    }

    fn update(&mut self) -> Vec<UpdateCommand> {
        self.ai.update(&mut self.state)
    }

    fn state(&'a self) -> &'a SpriteState {
        &self.state
    }

    fn modify_hp(&mut self, hp_mod: i16) {
        self.state.hp = std::cmp::max(self.state.hp as i16 + hp_mod, 0) as u16;
    }
}
